version: '3.7'
services:
  frontend:
    build: frontend
  backend:
    build: backend
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  nginx:
    restart: always
    build: nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data:
