version: '3.7'
services:
  frontend:
    logging:
      driver: 'none'
    build: frontend
    environment:
      - NODE_ENV=production
      - GA_MEASUREMENT_ID=
  backend:
    build: backend
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  dashboard_frontend:
    logging:
      driver: 'none'
    build: dashboard/frontend/
  dashboard_backend:
    build: dashboard/backend/
    environment:
      - NODE_ENV=production

  auth:
    restart: always
    build: auth
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  static:
    restart: always
    build: static
    volumes:
      - ./static/public:/static/public
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo
    logging:
      driver: 'none'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    command: mongod --enableFreeMonitoring on
  nginx:
    restart: always
    build: nginx
    ports:
      - 80:80
      - 7890:7890
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/bearer.lua:/bearer.lua
      - ./nginx/access.log:/var/log/nginx/access.log
      - goaccess_data:/www/goaccess
    depends_on:
      - frontend
      - backend
      - goaccess
      - dashboard_frontend
      - dashboard_backend
      - auth
      - static

  goaccess:
    build: dashboard/goaccess
    volumes:
      - ./nginx/access.log:/var/log/nginx/access.log
      - goaccess_data:/goaccess
    command: /var/log/nginx/access.log -o /goaccess/index.html --log-format=COMBINED --real-time-html --geoip-database /usr/share/GeoLite2-City/GeoLite2-City_20191224/GeoLite2-City.mmdb
volumes:
  mongodb_data:
  goaccess_data:
