version: '3.7'
services:
  frontend:
    build: frontend
  backend:
    build: backend
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  dashboard_frontend:
    build: dashboard/frontend/
  dashboard_backend:
    build: dashboard/backend/
    environment:
      - NODE_ENV=production

  auth:
    restart: always
    build: auth
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo
    logging:
      driver: 'none'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  nginx:
    restart: always
    build:
      context: nginx
      args:
        - jwtSecret=placeholder
    ports:
      - 80:80
      - 7890:7890
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./dashboard/GoAccess/index.html:/www/goaccess/index.html
    depends_on:
      - frontend
      - backend
      - goaccess
      - dashboard_frontend
      - dashboard_backend
      - auth

  goaccess:
    image: allinurl/goaccess
    volumes:
      - ./nginx/access.log:/goaccess/log/access.log
      - ./dashboard/GoAccess/index.html:/goaccess/index.html
    command: /goaccess/log/access.log -o /goaccess/index.html --log-format=COMBINED --real-time-html

volumes:
  mongodb_data:
